### ISSUE TITLE
Create default styling classes for easy re-use and same look everywhere

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#13]

**Comment by drikusroor** [comment]
What scenarios are you thinking about to use default styling classes?

**Comment by naomi-eliasar** [comment]
Maybe the buttons, although we could use the rw-button styling for that, but maybe we want a different color schema instead of the plain blue, red and green?

But also the cards we are currently using for the blog page and now also for the about page. So I can just give them the class to have the same look & feel, instead of styling them separately

**Comment by drikusroor** [comment]
I see. We are indeed currently using some `rw` (redwood) styling mixed with tailwindcss classes. [Tailwind has its own approach](https://tailwindcss.com/docs/reusing-styles) to reusing styles: Either copy-paste the utility classes (for real 😹 ) or create a component for it. If we want to go more for tailwind on this website, we might want to consider those options as well. And in the case of buttons, I think perhaps it might be best to create a button component with tailwind utility classes. Aside from that, if we're going to use tailwind mostly, we can define the color scheme in the tailwind config.

What do you think? Do you think we should go more for `rw` / css styling approach or for a tailwind approach?
