### ISSUE TITLE
Cloudinary stops scroll

### ISSUE THREAD

**Issue by Gakkenyak** [drikusroor/ohayo-goededagu#156]
Switchen naar Cloudinary bij het uploaden van een image in een post zorgt ervoor dat je niet meer kunt scrollen en dus kunt saven/publiceren

**Comment by Gakkenyak** [comment]
Ik heb dit geprobeerd te reproduceren, maar een tweede keer deed hij het wel. Misschien was het een eenmalige bug.

**Comment by naomi-eliasar** [comment]
Also can't reproduce
