### ISSUE TITLE
Name is not used in comments

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#189]
If someone posts a comment before setting his/her name in the account section, the comment keeps displaying his/her e-mail instead of the newly saved name.

The newly saved name is used in the displaying of who up/down voted

**Comment by Gakkenyak** [comment]
I saw this as well

**Comment by naomi-eliasar** [comment]
@drikusroor volgens mij heb je dit gefixt? of niet?

**Comment by drikusroor** [comment]
Yes 👌
