### ISSUE TITLE
Comments don't show in order

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#212]
The newest shows somewhere in the middle

![Image](https://github.com/drikusroor/ohayo-goededagu/assets/24891386/fa3b602c-9907-4c36-9806-5b435ba908af)

**Comment by drikusroor** [comment]
> The newest shows somewhere in the middle
> 
> ![Image](https://user-images.githubusercontent.com/24891386/270188077-fa3b602c-9907-4c36-9806-5b435ba908af.png)

That's a feature. They are sorted by amount of likes / dislikes 😅

**Comment by naomi-eliasar** [comment]
oh lol, haha oke 
nevermind 😆
