### ISSUE TITLE
We need a solution for storing / embeding images (could be internal or third-party)

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#35]
- [x] Have the possibility to upload a 'cover' picture for your blog article
- [ ] Have the possibility to upload pictures in the text of your article

Nice to have:
- [ ] The possibility to create and upload a gallery
- [ ] A photo gallery page that displays all uploaded pictures

Maybe we can use 'Cloudinary'?
![Image](https://user-images.githubusercontent.com/24891386/247249348-814766e6-a5ea-4bb9-98ec-e57e68e9aaaf.jpeg)

**Comment by drikusroor** [comment]
Yeah, if it has a free tier for us to use?
