### ISSUE TITLE
Create a way to give new accounts the right role

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#50]
Do we want an approval system for new users? @drikusroor @gakkenyak @adrianabm
If yes, should we add a text field to the signup for people to enter who they are and why they want to follow us? A 'let us know who you are' field?

## Proposed flow:
- [ ] If someone signs up they have to enter an email, password and a 'let us know who you are' field
- [ ] After signing up they become a 'GUEST', with just viewing rights (so they can see something right away and don't get discouraged if we take a few hours to approve them)
- [ ] If we allow someone they become a 'USER': they get access to a dashboard where they can upload/link their own profile picture, the bio is filled with the 'let us know who you are' field from the signup, they can comment and like on the posts

## Current available roles:
- GUEST (default)
- USER: crud comments
- MODERATOR: crud comments
- ADMIN: crud posts, crud comments

## Make:
- [ ] Add 'let us know who you are' field to the signup
- [ ] Change 'user' to 'email' in the signup & login form
- [ ] Add approval system to new signup accounts
- [ ] Implement proposed flow
- [ ] Create dashboard layout for USERs: Home, Account, Profile
- [ ] NTH: a 'liked' section on the dashboard, that shows an overview of your liked posts

## Technical approach:
* Create a function in `api/src/services/users/users.ts` that will be responsible for updating the roles of a user
  * You should never be able to unset the admin role if there is only one admin left
  * You can only execute this function if you - the logged in user - is an admin
* Create an `input` in `api/src/graphql/users.sdl.ts` for the required parameters of updating someone's roles. I imagine this to be `id` and an array of `role`.
* Create a form component in which you can edit the roles of a user `yarn rw g c AdminEditUserRoleForm`, which takes the following props: `user`, `onSave`, `error`, and `loading`.
* Create a `AdminEditUserRoleCell` cell that will be responsible for fetching the user with role data and posting the updated user role data. I think you can do `yarn rw g cell AdminEditUserRoleCell` [or something](https://redwoodjs.com/docs/cli-commands#generate-alias-g). This cell component should import and display the `AdminEditUserRoleForm` component.
* Create a `AdminEditUserRole` page, `yarn rw g page AdminEditUserRolePage`, which should then import and display the `AdminEditUserRoleCell` component.

See also here for how Redwood works with data: https://redwoodjs.com/docs/tutorial/chapter2/side-quest

Or check my own version of that overview:

![image](https://github.com/drikusroor/ohayo-goededagu/assets/8208970/d5b1cceb-a51e-4cf2-97e7-3972fdeae03a)

**Comment by Gakkenyak** [comment]
Wat is het verschil tussen moderator en admin role? In principe heb je een 'default' een 'bezoeker' (of user) die wij hebben goedgekeurd en dan heb je ons. Of je moet een super admin willen, dat kan natuurlijk, maar de rol voor ons moet in ieder geval ook in staat zijn comments te maken.

**Comment by naomi-eliasar** [comment]
> Wat is het verschil tussen moderator en admin role? In principe heb je een 'default' een 'bezoeker' (of user) die wij hebben goedgekeurd en dan heb je ons. Of je moet een super admin willen, dat kan natuurlijk, maar de rol voor ons moet in ieder geval ook in staat zijn comments te maken.

'crud' betekend create, read, update en delete

dus, admins zijn in staat om alles te doen voor posts en comments:

> Current available roles:
    GUEST (default)
    USER: crud comments
    MODERATOR: crud comments
    ADMIN: crud posts, crud comments
