### ISSUE TITLE
Show who up/down voted

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#65]
- [ ] Show who up/down voted on the comments
- [ ] Show who up/down voted on the posts

**Comment by Gakkenyak** [comment]
Of ipv een upvote/downvote (want wie gaat dit downvoten) een like knop, maar waarbij je wel kunt zien wie liked (aangezien iedereen een account heeft.) dan kunnen mensen ook interactie hebben zonder meteen een reactie achter te laten.
