### ISSUE TITLE
The post content edit input needs to become a WYSIWYG editor so it's easier to use

### ISSUE THREAD

**Issue by drikusroor** [drikusroor/ohayo-goededagu#7]
![Schermafbeelding 2023-06-15 172929](https://github.com/drikusroor/ohayo-goededagu/assets/8208970/008ce02f-66ae-4edd-bcf4-add861eb3dbf)

@adrianabm @naomi-eliasar we have to pick between some WYSIWYG editors. Do we want to use a Markdown (top) or HTML (bottom) WYSIWYG editor? Vote 🎉  for Markdown and 🚀  for HTML.

**Comment by naomi-eliasar** [comment]
I think the HTML might be easier in use. 
Although the markdown one is also nice because it looks like it will be easier to add links and even pictures?
