### ISSUE TITLE
Comment counter: fix number in light mode

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#79]
invisible numbers in light mode for all posts types but the article one (all that don't have a background)

![Image](https://user-images.githubusercontent.com/24891386/253885496-3837aa3a-239b-40ac-ac01-6c4d713c0df2.png)

**Comment by Gakkenyak** [comment]
Is er een Dark Mode?

**Comment by naomi-eliasar** [comment]
Ja, gewoon je browser/systeem dark mode
