### ISSUE TITLE
Posts aanpasbaar maken door verschillende (top)users in dashboard

### ISSUE THREAD

**Issue by Gakkenyak** [drikusroor/ohayo-goededagu#80]
Mogelijk maken om elkaars posts aan te passen en te zien in het cms. 

- [x] Show all posts by all authors in the Post Dashboard
- [ ] All admin's can edit all posts

**Comment by Gakkenyak** [comment]
Sorteerfunctie is misschien ook een apart issue?

**Comment by naomi-eliasar** [comment]
Ja, en ik denk dat een menu-item aanmaken voor je eigen posts is makkelijker dan een hele sorteerfunctie maken in de bestaande posts menu-item

**Comment by naomi-eliasar** [comment]
Willen we dat alle admin's behalve bewerken ook alle posts kunnen verwijderen?
